<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Reflection Enumerator</Title>
    <Authors>JPS</Authors>
    <Company>$(Authors)</Company>
    <Description>Creates an enumeration of reflected objects within a dll that can be easily consumed.</Description>
    <RepositoryUrl>https://github.com/zerihal/ReflectionEnumerator</RepositoryUrl>
    <NeutralLanguage>en-GB</NeutralLanguage>
    <PackageId>Reflection.Enumerator</PackageId>
    <Version>1.0.3-alpha.7</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.5" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>

</Project>
