<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Reflection Enumerator</Title>
    <Authors>JPS</Authors>
    <Company>$(Authors)</Company>
    <Description>Creates an enumeration of reflected objects within a dll that can be easily consumed.</Description>
    <RepositoryUrl>https://github.com/zerihal/ReflectionEnumerator</RepositoryUrl>
    <NeutralLanguage>en-GB</NeutralLanguage>
    <PackageId>Reflection.Enumerator</PackageId>
    <Version>2.0.0-alpha.2</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0.1</FileVersion>
    <PackageTags>.NET;Reflection;Reflection-API;Tool;Reflection mapping;Assembly analysis</PackageTags>
    <Copyright>JPS</Copyright>
    <PackageProjectUrl>https://github.com/zerihal/ReflectionEnumerator</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.5" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>

</Project>
