name: Dev CI/CD Pipeline

# Define permissions
permissions:
  contents: write  # Allows write access to the repository contents

on:
  push:
    branches:
      - Dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # 3. Increment version
      - name: Increment version
        run: |
          # Extract the current version
          current_version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' ./ReflectionEnumerator/ReflectionEnumerator.csproj)
      
          # Parse the numeric suffix after 'alpha.'
          prefix=$(echo "$current_version" | grep -oP '^[0-9]+\.[0-9]+\.[0-9]+-alpha\.' | head -n 1)
          suffix=$(echo "$current_version" | grep -oP '(?<=-alpha\.)[0-9]+' | head -n 1)
      
          # Increment the numeric suffix
          new_suffix=$((suffix + 1))
      
          # Construct the new version
          new_version="${prefix}${new_suffix}"
      
          # Replace the version in the .csproj file
          sed -i "s|<Version>$current_version</Version>|<Version>$new_version</Version>|g" ./ReflectionEnumerator/ReflectionEnumerator.csproj
      
          # Debugging: Output new version
          echo "Updated version: $new_version"

      # 4. Build the project
      - name: Build
        run: dotnet build --configuration Release

      # 5. Run tests
      - name: Run tests
        run: dotnet test --configuration Release

      # 6. Publish nuget package
      - name: Publish NuGet package to GitHub Packages
        run: |
          dotnet pack --configuration Release --output ./bin/Release
          dotnet nuget push ./bin/Release/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}

      # 7. Commit and push changes to the repo
      - name: Commit and push changes to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated build, version increment, and package push"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
