name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - Dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # 3. Increment version
      - name: Increment version
        run: |
          current_version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' ./ReflectionEnumerator/ReflectionEnumerator.csproj)
          new_version=$(echo $current_version | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+-alpha_)([0-9]+)/echo \1$((${BASH_REMATCH[2]} + 1))/e')
          sed -i "s|<Version>$current_version</Version>|<Version>$new_version</Version>|g" ./ReflectionEnumerator/ReflectionEnumerator.csproj

      # 4. Build the project
      - name: Build
        run: dotnet build --configuration Release

      # 5. Run tests
      - name: Run tests
        run: dotnet test --configuration Release

      # 6. Push the package
      - name: Push package
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated package push"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
